@echo off
setlocal enabledelayedexpansion
title GRBL CH32V307 - Generate .clangd

:: ============================================================
::  make_clangd.bat
::  Auto-generate .clangd for clangd language server
::  Run this script from project root to regenerate .clangd
::
::  Usage: .\scripts\make_clangd.bat
:: ============================================================

set "PROJECT_ROOT=%~dp0.."
for %%I in ("%PROJECT_ROOT%") do set "PROJECT_ROOT=%%~fI"

echo.
echo =============================================================
echo   Generate .clangd for clangd Language Server
echo   Project: %PROJECT_ROOT%
echo =============================================================
echo.

:: ============================================================
::  Auto-detect Toolchain (prefer GCC8 for CH32V307)
:: ============================================================
set "TOOLCHAIN_BASE=C:\MounRiver\MounRiver_Studio2\resources\app\resources\win32\components\WCH\Toolchain"

set "TC_DIR=%TOOLCHAIN_BASE%\RISC-V Embedded GCC"
set "GCC_TUPLE=riscv-none-embed"
set "GCC_VER=8.2.0"
set "TC_LABEL=RISC-V Embedded GCC"

if not exist "%TC_DIR%\bin\%GCC_TUPLE%-gcc.exe" (
    set "TC_DIR=%TOOLCHAIN_BASE%\RISC-V Embedded GCC12"
    set "GCC_TUPLE=riscv-wch-elf"
    set "GCC_VER=12.2.0"
    set "TC_LABEL=RISC-V Embedded GCC12"
)

if not exist "%TC_DIR%\bin\%GCC_TUPLE%-gcc.exe" (
    echo [ERROR] MounRiver toolchain not found at:
    echo         %TOOLCHAIN_BASE%
    echo   Please check MounRiver Studio 2 installation.
    goto :FAIL
)
echo [OK] Toolchain : %TC_LABEL%
echo [OK] Compiler  : %GCC_TUPLE%-gcc.exe

:: Convert paths to forward slashes
set "TC_DIR_FWD=%TC_DIR:\=/%"
set "PROJECT_FWD=%PROJECT_ROOT:\=/%"

:: ============================================================
::  Write .clangd
:: ============================================================
echo.
echo --- Writing .clangd ---

set "OUT=%PROJECT_ROOT%\.clangd"

:: Write header
(
echo # ============================================================
echo #  .clangd - auto-generated by make_clangd.bat
echo #  Project  : GRBL CH32V307 ^(6-Axis CNC Controller^)
echo #  MCU      : CH32V307 ^(rv32imafc, 144MHz, FPU^)
echo #           : CH32V203RBT6 ^(rv32imac, 144MHz, no FPU^)
echo #  Toolchain: %TC_LABEL% ^(%GCC_TUPLE%-gcc^)
echo #  Generated: %DATE% %TIME%
echo #  Re-run make_clangd.bat to update when project structure changes
echo # ============================================================
echo.
echo CompileFlags:
echo   Compiler: "%TC_DIR_FWD%/bin/%GCC_TUPLE%-gcc.exe"
echo.
echo   Add:
echo     # Force RISC-V 32-bit target
echo     - "--target=riscv32-unknown-elf"
echo.
echo     # Force C language for .h files
echo     - "-x"
echo     - "c"
echo.
echo     # C Standard
echo     - "-std=gnu99"
echo.
echo     # GCC system includes
echo     - "-I"
echo     - "%TC_DIR_FWD%/%GCC_TUPLE%/include"
echo     - "-I"
echo     - "%TC_DIR_FWD%/lib/gcc/%GCC_TUPLE%/%GCC_VER%/include"
echo     - "-I"
echo     - "%TC_DIR_FWD%/lib/gcc/%GCC_TUPLE%/%GCC_VER%/include-fixed"
echo.
echo     # Project include paths ^(relative - portable^)
) > "%OUT%"

:: Add project include paths
call :ADD_INC "grbl"
call :ADD_INC "mcu\CH32V307"
call :ADD_INC "mcu\CH32V307\sdk\Core"
call :ADD_INC "mcu\CH32V307\sdk\Debug"
call :ADD_INC "mcu\CH32V307\sdk\Peripheral\inc"
call :ADD_INC "mcu\CH32V203RBT6"
call :ADD_INC "mcu\CH32V203RBT6\sdk\Core"
call :ADD_INC "mcu\CH32V203RBT6\sdk\Debug"
call :ADD_INC "mcu\CH32V203RBT6\sdk\Peripheral\inc"

:: Write footer
(
echo.
echo     # Preprocessor Defines
echo     - "-D_DEBUG"
echo     # -- CH32V307 defines --
echo     - "-DCH32V30x"
echo     - "-DCH32V307"
echo     - "-DABC_AXIS_EXAMPLE"
echo     - "-DAB_AXIS"
echo     # -- CH32V203RBT6 defines --
echo     - "-DCH32V20x"
echo     - "-DCH32V203"
echo     - "-DCH32V203_RBT6_3AXIS"
echo.
echo     # Suppress false-positive warnings for embedded C
echo     - "-Wno-implicit-function-declaration"
echo     - "-Wno-int-conversion"
echo     - "-Wno-incompatible-pointer-types"
echo     - "-Wno-attributes"
echo.
echo   Remove:
echo     # Strip RISC-V / WCH-specific flags that clangd doesn't understand
echo     - "-march=rv32imafc"
echo     - "-march=rv32imac"
echo     - "-mabi=ilp32f"
echo     - "-mabi=ilp32"
echo     - "-msmall-data-limit=*"
echo     - "-msave-restore"
echo     - "-fsingle-precision-constant"
echo     - "-fmessage-length=*"
echo     - "-fno-common"
echo     - "-nostartfiles"
echo     - "-Xlinker"
echo     - "--gc-sections"
echo     - "--specs=*"
echo     - "-lm"
echo.
echo Diagnostics:
echo   UnusedIncludes: None
echo   Suppress:
echo     # Prevent "main file cannot be included recursively" when clangd opens .h
echo     - "pp_including_mainfile_in_preamble"
echo   ClangTidy:
echo     Remove:
echo       - "modernize-*"
echo       - "cppcoreguidelines-*"
echo       - "readability-*"
echo       - "performance-*"
echo       - "bugprone-reserved-identifier"
echo       - "cert-dcl37-c"
echo       - "cert-dcl51-cpp"
echo.
echo Index:
echo   Background: Build
) >> "%OUT%"

echo.
echo =============================================================
echo   [OK] Created: .clangd
echo.
echo   Press Ctrl+Shift+P in VS Code then select:
echo     "clangd: Restart Language Server"
echo =============================================================
echo.
goto :EOF


:: ============================================================
::  Subroutine: ADD_INC "relative\path"
::  Add include path if directory exists
:: ============================================================
:ADD_INC
    set "DIR=%PROJECT_ROOT%\%~1"
    if exist "%DIR%" (
        set "REL_FWD=%~1"
        set "REL_FWD=!REL_FWD:\=/!"
        echo     - "-I">> "%OUT%"
        echo     - "!REL_FWD!">> "%OUT%"
        echo   [+] %~1
    ) else (
        echo   [SKIP] %~1 ^(not found^)
    )
    exit /b 0


:FAIL
echo.
echo =============================================================
echo   [ERROR] Failed to generate .clangd
echo =============================================================
echo.
exit /b 1
