@echo off
setlocal enabledelayedexpansion
title GRBL CH32V307 - Generate .clangd

:: ============================================================
::  make_clangd.bat
::  Auto-generate .clangd for clangd language server
::  Run this script from project root to regenerate .clangd
::
::  Usage: .\scripts\make_clangd.bat
:: ============================================================

set "PROJECT_ROOT=%~dp0.."
for %%I in ("%PROJECT_ROOT%") do set "PROJECT_ROOT=%%~fI"

echo.
echo =============================================================
echo   Generate .clangd for clangd Language Server
echo   Project: %PROJECT_ROOT%
echo =============================================================
echo.

:: ============================================================
::  Auto-detect Active MCU Configuration from build.bat
:: ============================================================
set "MCU_CONFIG="
for /f "tokens=*" %%A in ('findstr /i "call.*mcu_config_" "%PROJECT_ROOT%\scripts\build.bat" ^| findstr /i /v "::"') do (
    set "LINE=%%A"
    set "LINE=!LINE:*mcu_config_=mcu_config_!"
    set "LINE=!LINE:"=!"
    set "MCU_CONFIG=!LINE!"
)
if "!MCU_CONFIG!"=="" (
    echo [WARNING] Active MCU configuration could not be detected. Defaulting to CH32V307.
    set "MCU_CONFIG=mcu_config_CH32V307.bat"
)

:: Run the configuration to import its variables
if exist "%PROJECT_ROOT%\scripts\!MCU_CONFIG!" (
    call "%PROJECT_ROOT%\scripts\!MCU_CONFIG!"
    echo [OK] Detected active config : !MCU_CONFIG!
    echo [OK] Detected active MCU    : !MCU_NAME!
) else (
    echo [WARNING] Configuration file !MCU_CONFIG! not found. Defaulting to CH32V307.
    set "MCU_NAME=CH32V307"
    set "MCU_FOLDER=mcu\CH32V307"
    set "DEFINES=-DCH32V307 -DABC_AXIS_EXAMPLE -DAB_AXIS"
    set "TOOLCHAIN_CHOICE=1"
)

:: ============================================================
::  Auto-detect Toolchain (based on TOOLCHAIN_CHOICE)
:: ============================================================
set "TOOLCHAIN_BASE=C:\MounRiver\MounRiver_Studio2\resources\app\resources\win32\components\WCH\Toolchain"

if "!TOOLCHAIN_CHOICE!"=="2" (
    set "TC_DIR=%TOOLCHAIN_BASE%\RISC-V Embedded GCC12"
    set "GCC_TUPLE=riscv-wch-elf"
    set "GCC_VER=12.2.0"
    set "TC_LABEL=RISC-V Embedded GCC12"
) else (
    set "TC_DIR=%TOOLCHAIN_BASE%\RISC-V Embedded GCC"
    set "GCC_TUPLE=riscv-none-embed"
    set "GCC_VER=8.2.0"
    set "TC_LABEL=RISC-V Embedded GCC"
)

if not exist "%TC_DIR%\bin\%GCC_TUPLE%-gcc.exe" (
    :: Fallback if selected toolchain not found
    if "!TOOLCHAIN_CHOICE!"=="2" (
        set "TC_DIR=%TOOLCHAIN_BASE%\RISC-V Embedded GCC"
        set "GCC_TUPLE=riscv-none-embed"
        set "GCC_VER=8.2.0"
        set "TC_LABEL=RISC-V Embedded GCC"
    ) else (
        set "TC_DIR=%TOOLCHAIN_BASE%\RISC-V Embedded GCC12"
        set "GCC_TUPLE=riscv-wch-elf"
        set "GCC_VER=12.2.0"
        set "TC_LABEL=RISC-V Embedded GCC12"
    )
)

if not exist "%TC_DIR%\bin\%GCC_TUPLE%-gcc.exe" (
    echo [ERROR] MounRiver toolchain not found at:
    echo         %TOOLCHAIN_BASE%
    echo   Please check MounRiver Studio 2 installation.
    goto :FAIL
)
echo [OK] Toolchain : %TC_LABEL%
echo [OK] Compiler  : %GCC_TUPLE%-gcc.exe

:: Convert paths to forward slashes
set "TC_DIR_FWD=%TC_DIR:\=/%"
set "PROJECT_FWD=%PROJECT_ROOT:\=/%"
set "MCU_FOLDER_FWD=%MCU_FOLDER:\=/%"

:: ============================================================
::  Write .clangd
:: ============================================================
echo.
echo --- Writing .clangd ---

set "OUT=%PROJECT_ROOT%\.clangd"

:: Write Block 1: Base settings
echo # ============================================================ > "%OUT%"
echo #  .clangd - auto-generated by make_clangd.bat >> "%OUT%"
echo #  Project  : GRBL CH32V307 ^(6-Axis CNC Controller^) >> "%OUT%"
echo #  Active MCU : %MCU_NAME% >> "%OUT%"
echo #  Generated: %DATE% %TIME% >> "%OUT%"
echo #  This file uses target-specific multi-config blocks to prevent IDE errors. >> "%OUT%"
echo # ============================================================ >> "%OUT%"
echo. >> "%OUT%"
echo # ------------------------------------------------------------ >> "%OUT%"
echo #  Block 1: Common Base Settings ^(Applies to all files^) >> "%OUT%"
echo # ------------------------------------------------------------ >> "%OUT%"
echo CompileFlags: >> "%OUT%"
echo   Add: >> "%OUT%"
echo     - "--target=riscv32-unknown-elf" >> "%OUT%"
echo     - "-x" >> "%OUT%"
echo     - "c" >> "%OUT%"
echo     - "-std=gnu99" >> "%OUT%"
echo. >> "%OUT%"
echo     # Suppress false-positive warnings for embedded C >> "%OUT%"
echo     - "-Wno-implicit-function-declaration" >> "%OUT%"
echo     - "-Wno-int-conversion" >> "%OUT%"
echo     - "-Wno-incompatible-pointer-types" >> "%OUT%"
echo     - "-Wno-attributes" >> "%OUT%"
echo     - "-Wno-unknown-attributes" >> "%OUT%"
echo     - "-Wno-ignored-attributes" >> "%OUT%"
echo. >> "%OUT%"
echo   Remove: >> "%OUT%"
echo     - "-march=*" >> "%OUT%"
echo     - "-mabi=*" >> "%OUT%"
echo     - "-msmall-data-limit=*" >> "%OUT%"
echo     - "-msave-restore" >> "%OUT%"
echo     - "-fsingle-precision-constant" >> "%OUT%"
echo     - "-fmessage-length=*" >> "%OUT%"
echo     - "-fno-common" >> "%OUT%"
echo     - "-nostartfiles" >> "%OUT%"
echo     - "-Xlinker" >> "%OUT%"
echo     - "--gc-sections" >> "%OUT%"
echo     - "--specs=*" >> "%OUT%"
echo     - "-lm" >> "%OUT%"
echo. >> "%OUT%"
echo Diagnostics: >> "%OUT%"
echo   UnusedIncludes: None >> "%OUT%"
echo   Suppress: >> "%OUT%"
echo     - "pp_including_mainfile_in_preamble" >> "%OUT%"
echo     - "drv_unknown_argument" >> "%OUT%"
echo     - "ignored_attributes" >> "%OUT%"
echo     - "unknown_attribute" >> "%OUT%"
echo   ClangTidy: >> "%OUT%"
echo     Remove: >> "%OUT%"
echo       - "modernize-*" >> "%OUT%"
echo       - "cppcoreguidelines-*" >> "%OUT%"
echo       - "readability-*" >> "%OUT%"
echo       - "performance-*" >> "%OUT%"
echo       - "bugprone-reserved-identifier" >> "%OUT%"
echo       - "cert-dcl37-c" >> "%OUT%"
echo       - "cert-dcl51-cpp" >> "%OUT%"
echo. >> "%OUT%"
echo Index: >> "%OUT%"
echo   Background: Build >> "%OUT%"

:: Write Block 2: CH32V307 files
echo. >> "%OUT%"
echo --- >> "%OUT%"
echo # ------------------------------------------------------------ >> "%OUT%"
echo #  Block 2: CH32V307 Specific Directory ^(GCC8^) >> "%OUT%"
echo # ------------------------------------------------------------ >> "%OUT%"
echo If: >> "%OUT%"
echo   PathMatch: mcu/CH32V307/.* >> "%OUT%"
echo. >> "%OUT%"
echo CompileFlags: >> "%OUT%"
echo   Compiler: "C:/MounRiver/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/RISC-V Embedded GCC/bin/riscv-none-embed-gcc.exe" >> "%OUT%"
echo   Add: >> "%OUT%"
echo     - "-isystem" >> "%OUT%"
echo     - "C:/MounRiver/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/RISC-V Embedded GCC/riscv-none-embed/include" >> "%OUT%"
echo     - "-isystem" >> "%OUT%"
echo     - "C:/MounRiver/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/RISC-V Embedded GCC/lib/gcc/riscv-none-embed/8.2.0/include" >> "%OUT%"
echo     - "-isystem" >> "%OUT%"
echo     - "C:/MounRiver/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/RISC-V Embedded GCC/lib/gcc/riscv-none-embed/8.2.0/include-fixed" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/grbl" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/mcu/CH32V307" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/mcu/CH32V307/sdk/Core" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/mcu/CH32V307/sdk/Debug" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/mcu/CH32V307/sdk/Peripheral/inc" >> "%OUT%"
echo     - "-DCH32V30x" >> "%OUT%"
echo     - "-DCH32V307" >> "%OUT%"
echo     - "-DABC_AXIS_EXAMPLE" >> "%OUT%"
echo     - "-DAB_AXIS" >> "%OUT%"
echo     - "-D_DEBUG" >> "%OUT%"

:: Write Block 3: CH32V203RBT6 files
echo. >> "%OUT%"
echo --- >> "%OUT%"
echo # ------------------------------------------------------------ >> "%OUT%"
echo #  Block 3: CH32V203RBT6 Specific Directory ^(GCC12^) >> "%OUT%"
echo # ------------------------------------------------------------ >> "%OUT%"
echo If: >> "%OUT%"
echo   PathMatch: mcu/CH32V203RBT6/.* >> "%OUT%"
echo. >> "%OUT%"
echo CompileFlags: >> "%OUT%"
echo   Compiler: "C:/MounRiver/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/RISC-V Embedded GCC12/bin/riscv-wch-elf-gcc.exe" >> "%OUT%"
echo   Add: >> "%OUT%"
echo     - "-isystem" >> "%OUT%"
echo     - "C:/MounRiver/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/RISC-V Embedded GCC12/riscv-wch-elf/include" >> "%OUT%"
echo     - "-isystem" >> "%OUT%"
echo     - "C:/MounRiver/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/RISC-V Embedded GCC12/lib/gcc/riscv-wch-elf/12.2.0/include" >> "%OUT%"
echo     - "-isystem" >> "%OUT%"
echo     - "C:/MounRiver/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/RISC-V Embedded GCC12/lib/gcc/riscv-wch-elf/12.2.0/include-fixed" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/grbl" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/mcu/CH32V203RBT6" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/mcu/CH32V203RBT6/sdk/Core" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/mcu/CH32V203RBT6/sdk/Debug" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/mcu/CH32V203RBT6/sdk/Peripheral/inc" >> "%OUT%"
echo     - "-DCH32V20x" >> "%OUT%"
echo     - "-DCH32V203_RBT6_3AXIS" >> "%OUT%"
echo     - "-D_DEBUG" >> "%OUT%"

:: Write Block 4: Shared GRBL Files (dynamically matches active target config)
echo. >> "%OUT%"
echo --- >> "%OUT%"
echo # ------------------------------------------------------------ >> "%OUT%"
echo #  Block 4: Shared GRBL Files ^(Uses Active MCU: %MCU_NAME%^) >> "%OUT%"
echo # ------------------------------------------------------------ >> "%OUT%"
echo If: >> "%OUT%"
echo   PathMatch: grbl/.* >> "%OUT%"
echo. >> "%OUT%"
echo CompileFlags: >> "%OUT%"
echo   Compiler: "%TC_DIR_FWD%/bin/%GCC_TUPLE%-gcc.exe" >> "%OUT%"
echo   Add: >> "%OUT%"
echo     - "-isystem" >> "%OUT%"
echo     - "%TC_DIR_FWD%/%GCC_TUPLE%/include" >> "%OUT%"
echo     - "-isystem" >> "%OUT%"
echo     - "%TC_DIR_FWD%/lib/gcc/%GCC_TUPLE%/%GCC_VER%/include" >> "%OUT%"
echo     - "-isystem" >> "%OUT%"
echo     - "%TC_DIR_FWD%/lib/gcc/%GCC_TUPLE%/%GCC_VER%/include-fixed" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/grbl" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/%MCU_FOLDER_FWD%" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/%MCU_FOLDER_FWD%/sdk/Core" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/%MCU_FOLDER_FWD%/sdk/Debug" >> "%OUT%"
echo     - "-I" >> "%OUT%"
echo     - "%PROJECT_FWD%/%MCU_FOLDER_FWD%/sdk/Peripheral/inc" >> "%OUT%"
echo     - "-D_DEBUG" >> "%OUT%"

:: Write active defines for Block 4
if "!MCU_NAME!"=="CH32V307" (
    echo     - "-DCH32V30x" >> "%OUT%"
) else (
    echo     - "-DCH32V20x" >> "%OUT%"
)
for %%D in (%DEFINES%) do (
    echo     - "%%D" >> "%OUT%"
)

:: ============================================================
::  Strip trailing spaces from every line using PowerShell
:: ============================================================
echo.
echo --- Cleaning up trailing spaces ---
powershell -NoProfile -Command "(Get-Content '%OUT%') | ForEach-Object { $_.TrimEnd() } | Set-Content -Encoding UTF8 '%OUT%'"

echo.
echo =============================================================
echo   [OK] Created: .clangd
echo.
echo   Press Ctrl+Shift+P in VS Code then select:
echo     "clangd: Restart Language Server"
echo =============================================================
echo.
goto :EOF

:FAIL
echo.
echo =============================================================
echo   [ERROR] Failed to generate .clangd
echo =============================================================
echo.
exit /b 1
